#!/usr/bin/env python3
"""Static contract tests for the standalone attribution comparison dashboard."""

from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parent
HTML_PATH = ROOT / "index.html"


class FrontendContractTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.html = HTML_PATH.read_text(encoding="utf-8")

    def run_inline_javascript_probe(self, probe: str) -> None:
        node = shutil.which("node")
        if not node:
            self.skipTest("node is not installed")
        scripts = re.findall(r"<script(?:\s[^>]*)?>([\s\S]*?)</script>", self.html, re.I)
        self.assertTrue(scripts, "inline JavaScript was not found")
        marker = "  bootstrap();\n})();"
        self.assertIn(marker, scripts[-1], "dashboard bootstrap marker changed")
        executable = scripts[-1].replace(marker, f"{probe}\n}})();", 1)
        with tempfile.TemporaryDirectory() as temp_dir:
            script_path = Path(temp_dir) / "dashboard-probe.js"
            script_path.write_text(executable, encoding="utf-8")
            result = subprocess.run(
                [node, str(script_path)],
                text=True,
                capture_output=True,
                timeout=20,
                check=False,
            )
        self.assertEqual(result.returncode, 0, result.stderr or result.stdout)

    def test_required_server_aggregation_endpoints(self) -> None:
        for endpoint in (
            "./api/meta",
            "./api/options",
            "./api/query",
            "./api/rankings",
            "./api/export.csv",
        ):
            self.assertIn(endpoint, self.html)
        self.assertNotRegex(
            self.html,
            r"(?<![A-Za-z])['\"]/api/(?:meta|options|query|rankings|export\.csv)['\"]",
            "report API routes must remain scoped below the report path",
        )
        self.assertIn("new URL(path,document.baseURI)", self.html)
        self.assertIn("new URL(API.exportCsv,document.baseURI)", self.html)
        self.assertNotIn("new Blob", self.html, "CSV must be generated by the backend")
        self.assertIn("response.blob()", self.html)
        self.assertIn("URL.createObjectURL", self.html)
        self.assertIn("URL.revokeObjectURL", self.html)

    def test_query_contract_uses_whitelisted_parameters(self) -> None:
        required = (
            "start_date",
            "end_date",
            "dimensions",
            "metric_basis",
            "channel",
            "app_id",
            "optimizer_id",
            "country_group",
            "account_id",
            "campaign",
            "adset",
            "sort_by",
            "sort_dir",
            "data_version",
            "limit",
            "offset",
            "include_rankings",
        )
        for name in required:
            self.assertRegex(self.html, rf"['\"]{re.escape(name)}['\"]")

    def test_date_boundary_and_presets(self) -> None:
        self.assertGreaterEqual(self.html.count("2026-07-29"), 3)
        for label in ("今天", "昨天", "近3天", "近7天", "近30天", "全部"):
            self.assertIn(label, self.html)
        self.assertIn("最新可用日", self.html)
        self.assertIn("latest_previous", self.html)

    def test_null_revenue_does_not_fall_back_to_zero_roas(self) -> None:
        self.run_inline_javascript_probe(
            """
  const missingOld = metricModel({spend:100,d30_revenue:50});
  const missingNew = metricModel({spend:100,d7_revenue:25});
  if(missingOld.oldRoas !== null)throw new Error('missing D7 revenue became zero ROAS');
  if(missingNew.newRoas !== null)throw new Error('missing D30 revenue became zero ROAS');
  if(missingOld.newRoas !== 0.5)throw new Error('D30 ROAS fallback is incorrect');
  if(missingNew.oldRoas !== 0.25)throw new Error('D7 ROAS fallback is incorrect');
""".rstrip()
        )

    def test_failed_filter_request_marks_previous_results_stale(self) -> None:
        self.assertIn("function setResultsStale(stale)", self.html)
        self.assertIn("if(state.hasData)setResultsStale(true)", self.html)
        self.assertIn("主查询失败，排行未请求", self.html)
        self.assertIn("上次成功查询结果，不对应当前筛选条件", self.html)
        self.assertIn("setResultsStale(false)", self.html)

    def test_data_version_is_pinned_and_conflicts_reload_the_snapshot(self) -> None:
        self.assertIn("params.set('data_version',state.dataVersion)", self.html)
        self.assertIn("function recoverFromVersionConflict(error)", self.html)
        self.assertIn("error.status!==409", self.html)
        self.assertIn("state.dataVersion=''", self.html)
        self.assertIn("loadAll(false,false", self.html)

    def test_mapping_quality_is_reported_separately_for_d7_and_d30(self) -> None:
        self.assertIn("windowQuality(quality,'d7')", self.html)
        self.assertIn("windowQuality(quality,'d30')", self.html)
        self.assertIn("旧D7", self.html)
        self.assertIn("新D30", self.html)
        self.assertIn("source_scope_exclusions", self.html)
        self.assertIn("候选内未匹配", self.html)
        self.run_inline_javascript_probe(
            """
  const quality = {
    d7:{total_revenue_rows:100,mapped_revenue_rows:80,unmapped_revenue_rows:20},
    d30:{total_revenue_rows:200,mapped_revenue_rows:190,ambiguous_revenue_rows:10}
  };
  const d7 = windowQuality(quality,'d7');
  const d30 = windowQuality(quality,'d30');
  if(d7.total !== 100 || d7.mapped !== 80 || d7.coverage !== 0.8)throw new Error('D7 quality was mixed');
  if(d30.total !== 200 || d30.mapped !== 190 || d30.coverage !== 0.95)throw new Error('D30 quality was mixed');
""".rstrip()
        )

    def test_refresh_reloads_meta_and_parallelizes_dependent_requests(self) -> None:
        self.assertIn("cacheMode='default'", self.html)
        self.assertIn("fetchJson(API.meta,null,request.signal,'no-store')", self.html)
        self.assertGreaterEqual(self.html.count("Promise.all"), 2)
        self.assertIn("get('refreshBtn').addEventListener('click',()=>loadAll(false))", self.html)

    def test_rankings_are_lazy_and_do_not_block_primary_results(self) -> None:
        self.assertIn("queryParams.set('include_rankings','0')", self.html)
        self.assertIn("async function loadRankings(params", self.html)
        self.assertIn("fetchJson(API.rankings,params,state.rankingController.signal)", self.html)
        self.assertIn("renderPayload(payload);hideLoading();void loadRankings(rankingParams", self.html)
        self.assertIn("if(key===state.rankingKey)return key", self.html)
        self.assertIn("state.rankingStatus==='loading'||state.rankingStatus==='loaded'", self.html)
        self.assertIn("排行暂不可用", self.html)

    def test_input_and_option_races_remain_visibly_consistent(self) -> None:
        self.assertIn("if(previous&&!seen.has(previous))", self.html)
        self.assertIn("当前选择（该日期范围无可用项）", self.html)
        self.assertIn("function scheduleKeywordQuery()", self.html)
        self.assertIn("++state.requestSeq;if(state.controller)state.controller.abort()", self.html)
        self.assertIn("等待关键词输入完成", self.html)
        self.assertIn("clearTimeout(state.debounceTimer);state.debounceTimer=0", self.html)

    def test_filters_dimensions_and_metric_basis(self) -> None:
        for element_id in (
            "channelFilter",
            "appFilter",
            "optimizerFilter",
            "countryGroupFilter",
            "accountFilter",
            "campaignKeyword",
            "adsetKeyword",
        ):
            self.assertIn(f'id="{element_id}"', self.html)
        for dimension in (
            "dt",
            "campaign",
            "adset",
            "optimizer",
            "country_group",
            "channel",
            "delivery_product",
            "account",
            "matched_grain",
        ):
            self.assertRegex(self.html, rf"key:['\"]{re.escape(dimension)}['\"]")
        self.assertIn('data-basis="d0"', self.html)
        self.assertIn('data-basis="d7"', self.html)

    def test_comparison_kpis_rankings_and_quality_states(self) -> None:
        for text in (
            "共同花费",
            "旧D7归因",
            "新D30归因",
            "收入差额",
            "收入提升率",
            "Campaign 排行",
            "Ad Set 排行",
            "优化师排行",
            "国家组排行",
            "generated_at",
            "data_version",
            "source_max_updated_at",
            "未完结当日",
            "mapped_ratio",
            "ambiguous_revenue_rows",
            "新增",
        ):
            self.assertIn(text, self.html)
        self.assertIn("role=\"alert\"", self.html)
        self.assertIn("aria-live=\"polite\"", self.html)

    def test_no_external_runtime_dependency_or_detail_download(self) -> None:
        self.assertNotRegex(self.html, r'<script[^>]+src=["\']https?://')
        self.assertNotRegex(self.html, r'<link[^>]+href=["\']https?://')
        self.assertNotIn("latest.json", self.html)
        self.assertNotIn("detail.json", self.html)
        self.assertNotIn("indexedDB", self.html)
        self.assertNotIn("caches.open", self.html)

    def test_inline_javascript_parses_with_node(self) -> None:
        node = shutil.which("node")
        if not node:
            self.skipTest("node is not installed")
        scripts = re.findall(r"<script(?:\s[^>]*)?>([\s\S]*?)</script>", self.html, re.I)
        self.assertTrue(scripts, "inline JavaScript was not found")
        with tempfile.TemporaryDirectory() as temp_dir:
            script_path = Path(temp_dir) / "dashboard-inline.js"
            script_path.write_text("\n".join(scripts), encoding="utf-8")
            result = subprocess.run(
                [node, "--check", str(script_path)],
                text=True,
                capture_output=True,
                timeout=20,
                check=False,
            )
        self.assertEqual(result.returncode, 0, result.stderr or result.stdout)


if __name__ == "__main__":
    unittest.main()
