CREATE TABLE IF NOT EXISTS kunlunads_dev.ads_drama_material_job (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  job_id CHAR(32) NOT NULL,
  content_id VARCHAR(64) NOT NULL,
  app VARCHAR(64) NOT NULL DEFAULT '',
  country CHAR(16) NOT NULL DEFAULT '',
  language CHAR(16) NOT NULL DEFAULT '',
  drama_name VARCHAR(255) NOT NULL DEFAULT '',
  episode_start INT NOT NULL DEFAULT 0,
  episode_end INT NOT NULL DEFAULT 0,
  total_episodes INT NOT NULL DEFAULT 0,
  cover_source_url VARCHAR(1024) NOT NULL DEFAULT '',
  cover_16x9_url VARCHAR(1024) NOT NULL DEFAULT '',
  output_video_url VARCHAR(1024) NOT NULL DEFAULT '',
  cover_16x9_path VARCHAR(1024) NOT NULL DEFAULT '',
  output_video_path VARCHAR(1024) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'queued',
  error_message TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_job_id (job_id),
  KEY idx_content_id (content_id),
  KEY idx_status_updated_at (status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
