const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
 const server=http.createServer((req,res)=>{const file=path.join(process.cwd(),'static',decodeURIComponent(req.url.split('?')[0]));if(fs.existsSync(file)&&fs.statSync(file).isFile()){res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}else{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const origin='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],writes=[];
 page.on('pageerror',e=>errors.push(e.message));
 const t={id:'failed-cover',title:'封面生成失败测试任务',status:'generation_failed',phase:'cover',created_at:'2026-09-12T04:20:38Z',current_version:1,cover_source:'ai',material:{name:'测试素材'},channel:{name:'测试频道'},requirements:'16:9 横版封面',versions:[],cover_preview:null,can_review:false,can_retry:true,can_upload_cover:true,steps:[],publish_at:'2026-09-12T16:40:00Z',error:{message:'AI 生成的封面文件损坏或数据不完整，无法读取'},notification:{status:'none'}};
 await page.route('**/api/**',async route=>{const req=route.request(),u=new URL(req.url()),reply=(x)=>route.fulfill({contentType:'application/json',body:JSON.stringify(x)});if(req.method()==='POST'){writes.push({path:u.pathname,body:req.postDataJSON()});if(u.pathname.endsWith('/covers'))return reply({asset:{id:'uploaded-asset'}});if(u.pathname.endsWith('/review')){Object.assign(t,{status:'schedule_missed',can_upload_cover:false,can_retry:false,current_version:2,error:{message:'请重新安排发布时间'}});return reply({task:t});}}if(u.pathname.endsWith('/bootstrap'))return reply({enabled:true,source:{configured:true},settings:{},channels:[],can_manage_settings:false});if(u.pathname.endsWith('/tasks'))return reply({items:[t],total:1,counts:{all:1,failed:1}});if(u.pathname.includes('/tasks/'))return reply({task:t});return reply({authenticated:true,user:{name:'QA',role:'admin'},modules:['youtube_auto_publish']});});
 try{await page.goto(origin+'/youtube-publish.html');await page.locator('[data-task-id="failed-cover"] [data-action="details"]').first().click();await page.getByRole('button',{name:'上传封面',exact:true}).click();const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=1280;c.height=720;c.getContext('2d').fillRect(0,0,1280,720);return c.toDataURL('image/png').split(',')[1]});await page.locator('#manual-cover-file').setInputFiles({name:'cover.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.getByRole('button',{name:'确认使用此封面',exact:true}).waitFor();if(writes.length)throw Error('file selection mutated server');fs.mkdirSync('output/playwright/cover-recovery',{recursive:true});await page.screenshot({path:'output/playwright/cover-recovery/preview.png'});await page.setViewportSize({width:390,height:844});if(!await page.locator('.modal').evaluate(el=>el.getBoundingClientRect().right<=innerWidth))throw Error('mobile overflow');await page.getByRole('button',{name:'确认使用此封面',exact:true}).click();await page.getByText('封面已确认，请重新安排发布时间。',{exact:true}).waitFor();if(writes.length!==2||writes[1].body.action!=='manual'||writes[1].body.version!==1)throw Error('wrong mutation');if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({passed:8,writes:writes.map(x=>x.path),errors}));}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exit(1)});


