/* Isolated browser mocks: no YouTube writes or production requests. */
async (page) => {
  const checks=[],errors=[],calls=[];
  const check=(name,value)=>{if(!value)throw new Error(name);checks.push(name);};
  const reply=(route,data,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
  const origin=page.url().match(/^http:\/\/127\.0\.0\.1:\d+/)?.[0] || 'http://127.0.0.1:8877';
  const auth={authenticated:true,user:{name:'测试用户',role:'admin',is_admin:true,tenant_key:'test',permissions:{youtube_auto_publish:true}}};
  const checked='2026-09-11T04:00:00Z';
  const good={id:'good',name:'正常频道',eligible:true,auth_status:'verified',reason:'Token 与频道授权预检通过',checked_at:checked};
  const blocked={id:'blocked',name:'封面被拒绝频道',eligible:false,auth_status:'blocked',reason:'缺少自定义缩略图权限',checked_at:checked,thumbnail_permission:'denied',failure_at:'2026-09-11T03:00:00Z'};
  const unknown={id:'unknown',name:'未确认频道',auth_status:'unknown',reason:'鉴权结果未知'};
  const mat=(id,name)=>({id,name,macro_name:name,thumbnail_url:'',language:'en'});
  const warm={age_seconds:3,ttl_seconds:300,refreshing:false,stale:false};
  let authRoute,bootstrapRoute,holdAuth=true,holdBootstrap=true,channelCalls=0,checking=true,blockGood=false,failChannels=false,channelBackgroundError=false,holdMaterialRefresh=false,materialRefreshRoute,searchA,queuedMaterialRoute,queuedRefreshCalls=0,manager=true,verifyCalls=0,failVerify=true,recovered=false,verifyBody;
  page.on('pageerror',error=>errors.push(error.message));
  await page.unrouteAll({behavior:'ignoreErrors'});
  await page.route('**/navigation.json',route=>reply(route,[]));
  await page.route('**/api/**',route=>{
    const raw=route.request().url().replace(/^https?:\/\/[^/]+/,''),path=raw.split('?')[0],query=raw.split('?')[1]||''; const url={searchParams:{get:key=>decodeURIComponent((query.split('&').find(x=>x.startsWith(key+'='))||'').slice(key.length+1).replace(/\+/g,' '))}};calls.push(raw);
    if(path==='/api/ui/topbar'){if(holdAuth){authRoute=route;return;}return reply(route,auth);}
    if(path.endsWith('/bootstrap')){if(holdBootstrap){bootstrapRoute=route;return;}return reply(route,{settings:{default_description:'默认描述'},source:{configured:true},channels_loaded:false,enabled:true,can_manage_settings:manager});}
    if(path.endsWith('/channels/verify-thumbnail')){verifyCalls++;verifyBody=route.request().postDataJSON();if(failVerify)return reply(route,{ok:false,message:'核验请求结果待确认'},503);recovered=true;return reply(route,{ok:true});}
    if(path.endsWith('/tasks'))return reply(route,{items:[],total:0,counts:{all:0}});
    if(path.endsWith('/channels')){channelCalls++;if(channelBackgroundError)return reply(route,{channels:[],checking:false,error:'频道列表后台更新失败'});return reply(route,failChannels?{message:'频道接口暂不可用',ok:false}:{channels:[blockGood?{...good,eligible:false,auth_status:'blocked',reason:'授权失效'}:good,recovered?{...blocked,eligible:true,auth_status:'verified',thumbnail_permission:'verified'}:blocked,unknown,{id:'pending',name:'检查中频道',eligible:null,auth_status:'checking'}],checking,checked_at:checked},failChannels?503:200);}
    if(path.endsWith('/materials')){
      if(url.searchParams.get('search')==='queued'){if(url.searchParams.get('refresh')==='1'){queuedRefreshCalls++;return reply(route,{configured:true,items:[mat('queued','强刷素材')],cache:warm});}queuedMaterialRoute=route;return;}
      if(url.searchParams.get('refresh')==='1'&&holdMaterialRefresh){materialRefreshRoute=route;return;}
      if(url.searchParams.get('search')==='slow'){searchA=route;return;}
      if(url.searchParams.get('search')==='fast')return reply(route,{configured:true,items:[mat('fast','最新搜索素材')],cache:warm});
      if(url.searchParams.get('search')==='cold')return reply(route,{configured:true,items:[],cache:{...warm,refreshing:true,age_seconds:null}});
      return reply(route,{configured:true,items:[mat('1','默认预取素材')],cache:warm});
    }
    return reply(route,{error:'unexpected'},404);
  });
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(origin+'/youtube-publish.html',{waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>document.querySelector('#page-message').textContent.includes('加载'));
  await page.waitForTimeout(100);
  check('bootstrap and auth start concurrently',Boolean(authRoute&&bootstrapRoute));
  check('workspace stays hidden until authentication succeeds',await page.locator('#page-content').isHidden());
  await reply(authRoute,auth);holdAuth=false;
  await page.waitForTimeout(100);
  check('task read starts before bootstrap completes',calls.some(x=>x.includes('/tasks?')));
  check('workspace stays hidden until bootstrap permission succeeds',await page.locator('#page-content').isHidden());
  await reply(bootstrapRoute,{settings:{default_description:'默认描述'},source:{configured:true},channels_loaded:false,enabled:true,can_manage_settings:manager});holdBootstrap=false;
  await page.locator('#new-publish').click();
  await page.locator('#draft-channel option[value="unknown"]').waitFor({state:'attached'});
  check('all channels remain visible',await page.locator('#draft-channel option').count()===5);
  check('only explicit eligible true enables a channel',await page.locator('#draft-channel option').evaluateAll(options=>options.filter(o=>o.value).map(o=>[o.value,o.disabled])).then(rows=>rows.every(([id,disabled])=>disabled===(id!=='good'))));
  check('blocked reason appears in option',await page.locator('option[value="blocked"]').textContent().then(t=>t.includes('缺少自定义缩略图权限')));
  await page.locator('#draft-title').fill('鉴权期间保留标题');
  await page.locator('#draft-channel').selectOption('good');
  check('selected channel shows check time and reason',await page.locator('.channel-check-status').innerText().then(t=>t.includes('2026')&&t.includes('Token 与频道授权预检通过')));
  await page.waitForTimeout(2200);
  check('checking channels poll automatically',channelCalls>=2);
  check('polls never force refresh',calls.filter(x=>x.includes('/channels')).every(x=>!x.includes('refresh=1')));
  checking=false;blockGood=true;
  await page.locator('[data-action="retry-channels"]').click();
  await page.waitForTimeout(150);
  check('manual channel refresh requests fresh authentication',calls.some(x=>x.endsWith('/channels?refresh=1')));
  check('revoked selected channel is cleared',await page.locator('#draft-channel').inputValue()==='');
  check('channel refresh preserves mounted title input',await page.locator('#draft-title').inputValue()==='鉴权期间保留标题');
  failChannels=true;
  await page.locator('[data-action="retry-channels"]').click();
  await page.locator('#channel-state').waitFor();
  check('failed channel refresh keeps all channels visible but disables select',await page.locator('#draft-channel').isDisabled()&&await page.locator('#draft-channel option').count()===5);
  await page.locator('#draft-title').fill('失败仍可填写');
  check('channel failure permits unrelated draft edits',await page.locator('#draft-title').inputValue()==='失败仍可填写');
  failChannels=false;channelBackgroundError=true;
  await page.locator('[data-action="retry-channels"]').click();
  await page.waitForTimeout(100);
  check('HTTP 200 background channel error is visible',await page.locator('#channel-state').innerText().then(t=>t.includes('频道列表后台更新失败')));
  check('background channel error retains inventory and blocks selection',await page.locator('#draft-channel option').count()===5&&await page.locator('#draft-channel').isDisabled());
  channelBackgroundError=false;
  const prefetched=calls.filter(x=>x.includes('/materials?')).length;
  check('new publish prefetches default materials',prefetched===1);
  await page.locator('[data-action="choose-material"]').click();
  await page.locator('.material-card').waitFor();
  check('picker reuses prefetched materials without second request',calls.filter(x=>x.includes('/materials?')).length===prefetched);
  check('cache update time is visible',await page.locator('.material-cache-status').innerText().then(t=>t.includes('更新于')));
  await page.locator('.material-card').evaluate(node=>window.qaMaterialNode=node);
  holdMaterialRefresh=true;
  await page.locator('[data-action="reload-materials"]').click();
  await page.waitForTimeout(100);
  check('manual material refresh preserves existing cards',await page.locator('.material-card').evaluate(node=>window.qaMaterialNode===node));
  check('manual material refresh sends refresh flag',Boolean(materialRefreshRoute)&&calls.some(x=>x.includes('/materials?search=&refresh=1')));
  await reply(materialRefreshRoute,{configured:true,items:[mat('1','默认预取素材')],cache:warm});
  holdMaterialRefresh=false;
  await page.locator('#material-search').fill('slow');
  await page.waitForTimeout(350);
  check('slow search request is pending',Boolean(searchA));
  await page.locator('#material-search').fill('fast');
  // The old response arrives inside the debounce window of the new query.
  await reply(searchA,{configured:true,items:[mat('slow','旧搜索不得覆盖')],cache:warm});
  await page.waitForTimeout(400);
  check('late response cannot overwrite new search',await page.locator('.material-grid').innerText().then(t=>t.includes('最新搜索素材')&&!t.includes('旧搜索不得覆盖')));
  check('search text and DOM input survive asynchronous results',await page.locator('#material-search').inputValue()==='fast');
  await page.locator('#material-search').fill('queued');
  await page.waitForTimeout(350);
  check('ordinary material request remains in flight',Boolean(queuedMaterialRoute));
  await page.locator('#material-search').fill('fast');
  await page.waitForTimeout(350);
  await page.locator('#material-search').fill('queued');
  await page.locator('[data-action="reload-materials"]').click();
  await page.locator('#material-search').fill('fast');
  await page.waitForTimeout(350);
  await page.locator('#material-search').fill('queued');
  await page.locator('[data-action="reload-materials"]').click();
  await reply(queuedMaterialRoute,{configured:true,items:[mat('queued','旧普通请求素材')],cache:warm});
  await page.waitForTimeout(400);
  check('manual refresh waits then sends exactly one refresh request',queuedRefreshCalls===1);
  check('queued refresh result wins over older ordinary response',await page.locator('.material-grid').innerText().then(t=>t.includes('强刷素材')&&!t.includes('旧普通请求素材')));
  await page.clock.install();
  await page.locator('#material-search').fill('cold');
  await page.clock.runFor(400);
  await page.waitForTimeout(100);
  check('cold miss shows updating rather than false empty result',await page.locator('.material-grid').innerText().then(t=>t.includes('正在加载素材')&&!t.includes('暂无符合')));
  await page.clock.fastForward(92000);
  await page.waitForTimeout(200);
  check('material background polling stops with visible bounded timeout',await page.locator('.material-cache-status').innerText().then(t=>t.includes('已暂停自动查询')));
  const coldCalls=calls.filter(x=>x.includes('search=cold')).length;
  await page.clock.fastForward(6000);
  await page.waitForTimeout(100);
  check('no material polling continues after deadline',calls.filter(x=>x.includes('search=cold')).length===coldCalls);
  await page.locator('.modal-overlay:last-child .close-modal').click();
  failChannels=false;checking=true;
  await page.locator('[data-action="retry-channels"]').click();
  await page.waitForTimeout(100);
  await page.clock.fastForward(92000);
  await page.waitForTimeout(200);
  check('channel background polling has a visible 90 second deadline',await page.locator('.channel-check-status').innerText().then(t=>t.includes('已暂停自动查询')));
  const boundedChannels=channelCalls;
  await page.clock.fastForward(6000);
  await page.waitForTimeout(100);
  check('no channel polling continues after deadline',channelCalls===boundedChannels);
  checking=false;
  await page.locator('[data-action="retry-channels"]').click();
  await page.waitForTimeout(100);
  await page.locator('.channel-auth-details summary').click();
  await page.locator('[data-action="verify-thumbnail"]').click();
  check('administrator recovery requires explicit Studio confirmation',await page.locator('[data-action="confirm-thumbnail"]').isDisabled()&&verifyCalls===0);
  check('confirmation names the exact channel',await page.locator('.thumbnail-confirm').innerText().then(t=>t.includes(blocked.name)&&t.includes('YouTube Studio')));
  await page.locator('.modal-overlay:last-child .close-modal').click();
  check('canceling recovery never submits',verifyCalls===0);
  await page.locator('[data-action="verify-thumbnail"]').click();
  await page.locator('#studio-thumbnail-confirm').check();
  await page.locator('[data-action="confirm-thumbnail"]').click();
  await page.locator('.modal-overlay:last-child .inline-error').waitFor();
  check('recovery request binds channel and observed failure timestamp',verifyBody.channel_id===blocked.id&&verifyBody.failure_at===blocked.failure_at&&verifyBody.confirmation==='studio_thumbnail_verified');
  await page.waitForTimeout(200);
  check('uncertain recovery is never automatically retried',verifyCalls===1&&await page.locator('.modal-overlay:last-child .inline-error').innerText().then(t=>t.includes('不会自动重新提交')));
  failVerify=false;
  await page.locator('[data-action="confirm-thumbnail"]').click();
  await page.waitForTimeout(200);
  check('successful recorded recovery refreshes channel eligibility',verifyCalls===2&&await page.locator('#draft-channel option[value="blocked"]').evaluate(node=>!node.disabled));
  manager=false;recovered=false;
  await page.reload({waitUntil:'domcontentloaded'});
  await page.locator('#new-publish').click();
  await page.locator('#draft-channel option[value="blocked"]').waitFor({state:'attached'});
  await page.locator('.channel-auth-details summary').click();
  check('non administrator has no recovery button',await page.locator('[data-action="verify-thumbnail"]').count()===0);
  check('non administrator sees administrator contact guidance',await page.locator('.channel-auth-details').innerText().then(t=>t.includes('请联系管理员')));
  check('no JavaScript exceptions',errors.length===0);
  return {passed:checks.length,checks,errors};
}
