/* playwright-cli run-code --filename tests/youtube_publish_loading_qa.js
 * Uses isolated browser routes and real 12s/45s deadlines, never platform APIs. */
async (page) => {
  const checks=[],calls=[],errors=[];
  const check=(name,value)=>{if(!value)throw new Error(name);checks.push(name);};
  const respond=(route,data,status=200)=>route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
  const origin='http://127.0.0.1:8877';
  const material={id:'1',name:'测试素材',macro_name:'测试剧名',macro_desc:'测试简介',macro_url:'',long_url:'https://example.invalid/drama',source_job_id:'a'.repeat(32),content_id:'drama-1',url:'',thumbnail_url:'',language:'en',duration:'12:30'};
  const channel={id:'1',name:'测试频道',language:'en',eligible:true,comment_eligible:true};
  const auth={authenticated:true,user:{name:'测试用户',role:'admin',is_admin:true,tenant_key:'test',permissions:{youtube_auto_publish:true}}};
  let holdNavigation=true,holdTasks=true,holdChannels=true,holdAuth=false,failBootstrap=false,holdPost=false;
  let pendingTasks=null,postBody=null,created=null;
  page.on('pageerror',error=>errors.push(error.message));
  await page.unrouteAll({behavior:'ignoreErrors'});
  await page.route('**/navigation.json',route=>holdNavigation?undefined:respond(route,[{key:'youtube',label:'YouTube 社媒',items:[{key:'youtubeAutoPublish',label:'YouTube 自动发布',kind:'page',href:'/youtube-publish.html',module:'youtube_auto_publish',enabled:true}]}]));
  await page.route('**/api/**',async route=>{
    const request=route.request(),path=request.url().replace(/^https?:\/\/[^/]+/,'').split('?')[0];
    const body=request.postDataJSON();calls.push({path,url:request.url(),method:request.method(),body,at:Date.now()});
    if(path==='/api/ui/topbar')return holdAuth?undefined:respond(route,auth);
    if(path.endsWith('/bootstrap'))return failBootstrap?respond(route,{error:'temporary_failure',message:'暂时无法加载配置'},503):respond(route,{settings:{default_description:'{desc}'},source:{configured:true},channels:[],channels_loaded:false,enabled:true,can_manage_settings:true});
    if(path.endsWith('/channels'))return holdChannels?undefined:respond(route,{channels:[channel]});
    if(path.endsWith('/materials'))return respond(route,{configured:true,items:[material]});
    if(path.endsWith('/tasks')&&request.method()==='GET'){if(holdTasks){pendingTasks=route;return;}return respond(route,{items:created?[created]:[],total:created?1:0,counts:{all:created?1:0,review:0,running:created?1:0,published:0,failed:0}});}
    if(path.endsWith('/tasks')&&request.method()==='POST'){
      postBody=body;if(holdPost)return;
      created={id:'a'.repeat(32),title:'测试剧名',description:'测试简介',comment:'',title_template:body.title_template,description_template:body.description_template,comment_template:'',material,channel,cover_source:'ai',requirements:body.requirements,status:'queued_generation',phase:'cover',created_at:'2026-09-10T10:00:00Z',current_version:1,versions:[],steps:[],notification:{status:'none',message:''},can_review:false,can_retry:false};return respond(route,{task:created});
    }
    if(path.endsWith('/tasks/'+'a'.repeat(32)))return respond(route,{task:created});
    return respond(route,{error:'unexpected_route'},404);
  });
  await page.setViewportSize({width:1440,height:1000});
  const started=Date.now();
  await page.goto(origin+'/youtube-publish.html',{waitUntil:'domcontentloaded'});
  await page.locator('#page-content:not(.hidden)').waitFor();
  const workspaceMs=Date.now()-started;
  check('workspace appears while navigation request is still hung',workspaceMs<2000&&holdNavigation);
  check('lite bootstrap requested independently of navigation',calls.some(x=>x.url.includes('/bootstrap?include_channels=0')));
  check('channels not requested during bootstrap',!calls.some(x=>x.path.endsWith('/channels')));
  await page.getByRole('heading',{name:'正在加载发布任务',exact:true}).waitFor();
  check('initial tasks have explicit loading state',await page.locator('#task-table').innerText().then(t=>!t.includes('暂无发布任务')));
  check('initial counters do not pretend zero',await page.locator('#stats .stat-number').allTextContents().then(values=>values.every(x=>x==='—')));
  const opened=Date.now();
  await page.locator('#new-publish').click();
  await page.getByRole('heading',{name:'新建发布',exact:true}).waitFor();
  const modalMs=Date.now()-opened;
  check('publish dialog opens before channel response',modalMs<1000&&holdChannels);
  check('channel pending select disabled',await page.locator('#draft-channel').isDisabled());
  await page.locator('#draft-title').fill('正在等待频道也能填写标题');
  await page.locator('#draft-requirements').fill('16:9 横版封面');
  check('other draft fields editable while channels pending',await page.locator('#draft-title').inputValue()==='正在等待频道也能填写标题');
  await page.locator('[data-action="submit-publish"]').click();
  check('submit gated until channels successfully load',await page.locator('.error-message').allTextContents().then(values=>values.some(x=>x.includes('频道正在加载'))));
  holdTasks=false;
  if(pendingTasks)await respond(pendingTasks,{items:[],total:0,counts:{all:0,review:0,running:0,published:0,failed:0}});
  await page.locator('#channel-state').waitFor({timeout:15000});
  const channelCall=calls.find(x=>x.path.endsWith('/channels'));
  const channelTimeoutMs=Date.now()-channelCall.at;
  check('hung channel request ends after 12 second deadline',channelTimeoutMs>=11500&&channelTimeoutMs<14500);
  check('channel timeout retains entered draft',await page.locator('#draft-title').inputValue()==='正在等待频道也能填写标题');
  check('channel timeout does not auto retry',calls.filter(x=>x.path.endsWith('/channels')).length===1);
  holdChannels=false;
  await page.locator('[data-action="retry-channels"]').click();
  await page.locator('#draft-channel:not([disabled])').waitFor();
  await page.locator('#draft-channel').selectOption('1');
  check('manual channel retry restores eligible selection',await page.locator('#draft-channel').inputValue()==='1');
  await page.locator('.close-modal').click();
  const channelRequests=calls.filter(x=>x.path.endsWith('/channels')).length;
  await page.locator('#new-publish').click();
  await page.locator('#draft-channel:not([disabled])').waitFor();
  check('successful channel results reused within 60 seconds',calls.filter(x=>x.path.endsWith('/channels')).length===channelRequests);
  await page.locator('.close-modal').click();
  holdNavigation=false;holdAuth=true;
  await page.goto(origin+'/youtube-publish.html',{waitUntil:'domcontentloaded'});
  await page.waitForFunction(()=>document.querySelector('#refreshPage').dataset.topbarBound==='1');
  const authCalls=calls.filter(x=>x.path==='/api/ui/topbar').length;
  holdAuth=false;
  await page.locator('#refreshPage').click();
  await page.locator('#page-content:not(.hidden)').waitFor();
  check('refresh works before auth completed',calls.filter(x=>x.path==='/api/ui/topbar').length===authCalls+1);
  failBootstrap=true;
  await page.goto(origin+'/youtube-publish.html',{waitUntil:'domcontentloaded'});
  await page.locator('[data-action="retry-init"]').waitFor();
  check('initialization failure has retry control',await page.locator('#page-message').innerText().then(t=>t.includes('暂时无法加载配置')));
  failBootstrap=false;
  await page.locator('[data-action="retry-init"]').click();
  await page.locator('#page-content:not(.hidden)').waitFor();
  await page.locator('#new-publish').click();
  await page.locator('#draft-channel:not([disabled])').waitFor();
  check('retry initialization does not duplicate open-dialog events',await page.locator('.modal-overlay').count()===1);
  await page.locator('[data-action="choose-material"]').click();
  await page.locator('[data-action="select-material"]').click();
  await page.locator('[data-action="confirm-material"]').click();
  await page.locator('#draft-channel').selectOption('1');
  await page.locator('#draft-requirements').fill('16:9 横版，电影风格');
  holdPost=true;
  await page.locator('[data-action="submit-publish"]').click();
  await page.getByText('上次提交结果待确认。',{exact:false}).waitFor({timeout:50000});
  const firstPost=calls.find(x=>x.path.endsWith('/tasks')&&x.method==='POST');
  const postTimeoutMs=Date.now()-firstPost.at;
  check('POST deadline is 45 seconds',postTimeoutMs>=44500&&postTimeoutMs<48500);
  check('POST timeout keeps draft and operation identifier',await page.locator('#draft-title').inputValue()==='{name}'&&Boolean(postBody.operation_id));
  check('POST timeout locks frozen submission fields',await page.locator('#draft-title').isDisabled());
  check('POST timeout never automatically resubmits',calls.filter(x=>x.path.endsWith('/tasks')&&x.method==='POST').length===1);
  const originalOperation=postBody.operation_id;
  holdPost=false;
  await page.locator('[data-action="submit-publish"]').click();
  await page.getByRole('heading',{name:'发布任务详情',exact:true}).waitFor();
  check('explicit POST retry uses unchanged operation id',postBody.operation_id===originalOperation);
  check('no JavaScript exceptions',errors.length===0);
  return {passed:checks.length,workspaceMs,modalMs,channelTimeoutMs,postTimeoutMs,checks,errors};
}
