/* Run with playwright-cli run-code --filename tests/youtube_publish_browser_qa.js.
 * HTTP routes are isolated browser mocks; no production API or platform writes. */
async (page) => {
  const results = [], calls = [], errors = [];
  const check = (name,condition) => { if (!condition) throw new Error(name); results.push(name); };
  const fixture = {name:'qa-cover.png',mimeType:'image/png',buffer:await page.screenshot({type:'png'})};
  const origin = page.url().match(/^http:\/\/127\.0\.0\.1:\d+/)?.[0] || 'http://127.0.0.1:8877';
  const cover = origin + '/qa-cover.png';
  const material = {id:'material-1',name:'QA 素材',drama_cover_url:cover,drama_cover_status:'available',drama_cover_message:'',macro_name:'QA 剧名',macro_desc:'A story <script>window.bad=1</script>',macro_url:'',long_url:'https://www.dramawavew2a.com/ads/101/2284/view?af_dp=qa&c=ai_youtube&af_channel=ai_youtube&af_c_id=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',source_job_id:'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',content_id:'qa',url:'',thumbnail_url:cover,language:'英语',duration:'12:30',size:'80 MB'};
  const channel = {id:'channel-1',name:'QA 频道',language:'英语',eligible:true};
  let configured = false, stale = false, forceCreateFailure = false, count = 0, featureEnabled = true, loggedIn = true, permissionDenied = false;
  let defaultDescription = '{desc}\nWatch now: {url}';
  const task = (id,extra={}) => ({id,title:'QA 剧名',title_template:'{name}',description:'A story',description_template:'{desc}',comment:'',comment_template:'',material,channel,cover_source:'ai',requirements:'16:9 横版，突出人物',status:'review',phase:'review',created_at:'2026-09-10T07:00:00Z',cover_url:cover,current_version:1,versions:[{number:1,url:cover,feedback:'首次生成',created_at:'2026-09-10T07:00:00Z'}],steps:[{key:'upload',label:'私享上传视频',status:'pending',message:'等待封面确认'},{key:'thumbnail',label:'设置最终封面',status:'pending',message:'等待执行'},{key:'processing',label:'等待视频处理',status:'pending',message:'等待执行'},{key:'public',label:'公开视频',status:'pending',message:'等待执行'},{key:'comment',label:'发送首条评论',status:'skipped',message:'未填写，已跳过'}],notification:{status:'sent',message:'已发送审核提醒'},can_review:true,can_retry:false,...extra});
  let tasks = [task('review-1'),task('review-2'),task('review-3'),task('failed-1',{status:'comment_failed',can_review:false,can_retry:true,error:{code:'comment_failed',message:'首评发送失败，视频已公开'}})];
  const respond = (route,data,status=200) => route.fulfill({status,contentType:'application/json',body:JSON.stringify(data)});
  page.on('pageerror',e=>errors.push(e.message));
  await page.unrouteAll({behavior:'wait'});
  await page.route('**/qa-cover.png',route=>route.fulfill({status:200,contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720"><rect width="1280" height="720" fill="#183aa1"/><text x="80" y="360" font-size="90" fill="white">QA cover</text></svg>'}));
  await page.route('**/navigation.json',route=>respond(route,[{key:'youtube',label:'YouTube 社媒',items:[{key:'youtubeAutoPublish',label:'YouTube 自动发布',kind:'page',href:'/youtube-publish.html',module:'youtube_auto_publish',enabled:true}]}]));
  await page.route('**/api/**',async route=>{
    const request=route.request(),p=request.url().replace(/^https?:\/\/[^/]+/,'').split('?')[0],body=request.postDataJSON();
    calls.push({path:p,method:request.method(),body});
    if(p==='/api/ui/topbar')return respond(route,{authenticated:loggedIn,user:loggedIn?{name:'QA 用户',role:'admin',is_admin:true,tenant_key:'qa',permissions:{youtube_auto_publish:true}}:null});
    if(p.endsWith('/bootstrap'))return permissionDenied?respond(route,{error:{message:'当前用户没有此模块权限'}},403):respond(route,{settings:{default_description:defaultDescription},channels:[],channels_loaded:false,source:{configured},can_manage_settings:true,enabled:featureEnabled});
    if(p.endsWith('/channels'))return respond(route,{channels:[channel]});
    if(p.endsWith('/materials'))return respond(route,{configured,items:configured?[material]:[]});
    if(p.endsWith('/covers'))return respond(route,{asset:{id:'asset-1',url:cover}});
    if(p.endsWith('/settings')){defaultDescription=body.default_description;return respond(route,{settings:{default_description:defaultDescription}});}
    if(p.endsWith('/tasks')&&request.method()==='GET')return respond(route,{items:tasks,total:tasks.length,counts:{all:tasks.length,review:tasks.filter(x=>x.status==='review').length,published:1,failed:1,running:0}});
    if(p.endsWith('/tasks')&&request.method()==='POST'){
      if(forceCreateFailure){forceCreateFailure=false;return respond(route,{error:{message:'临时服务故障'}},503);}
      const t=task('created-'+(++count),{status:body.cover_source==='ai'?'generating':'uploading',can_review:false,title:body.title_template.replace('{name}',material.macro_name),title_template:body.title_template,description_template:body.description_template,comment_template:body.comment_template,comment:body.comment_template,cover_source:body.cover_source,requirements:body.requirements});tasks.unshift(t);return respond(route,{task:t});
    }
    const match=p.match(/\/tasks\/([^/]+)(?:\/(review|retry))?$/);
    if(match){const t=tasks.find(x=>x.id===match[1]);if(!t)return respond(route,{error:{message:'任务不存在'}},404);if(match[2]==='review'){
      if(stale){stale=false;t.current_version=2;t.versions.push({number:2,url:cover,feedback:'新版本',created_at:'2026-09-10T08:00:00Z'});return respond(route,{error:{message:'版本已更新'}},409);}
      t.status=body.action==='reject'?'generating':'uploading';t.can_review=false;return respond(route,{task:t});
    }if(match[2]==='retry'){t.status='uploading';t.can_retry=false;return respond(route,{task:t});}return respond(route,{task:t});}
    return respond(route,{error:{message:'Unexpected route '+p}},404);
  });
  await page.setViewportSize({width:1440,height:1000});
  await page.goto(origin + '/youtube-publish.html');
  await page.locator('#task-table tr').first().waitFor();
  check('production no demo action',await page.getByRole('button',{name:/模拟飞书提醒|重置演示|空态/}).count()===0);
  check('shared authenticated topbar',await page.locator('#userCard').innerText().then(t=>t.includes('QA 用户')));
  check('SQL unconfigured notice',await page.locator('#source-message').innerText().then(t=>t.includes('素材筛选规则待配置')));
  await page.locator('#new-publish').click();
  await page.locator('[data-action="submit-publish"]').click();
  check('required field validation',await page.locator('.error-message').count()>=3);
  await page.locator('[data-action="choose-material"]').click();
  await page.getByRole('heading',{name:'素材筛选规则待配置'}).waitFor();
  check('unconfigured SQL has no fake materials',await page.locator('.material-card').count()===0);
  await page.locator('.modal-overlay').last().locator('[data-action="close-modal"]').first().click();
  configured=true;
  await page.locator('[data-action="choose-material"]').click();
  await page.locator('[data-action="select-material"]').click();
  await page.locator('[data-action="confirm-material"]').click();
  check('selected macro name preview',await page.locator('[data-macro-preview="title"]').innerText().then(t=>t.includes('QA 剧名')));
  check('pending URL preview',await page.locator('[data-macro-preview="description"]').innerText().then(t=>t.includes('提交时生成跳转链接')));
  check('macro source escaped',await page.evaluate(()=>!window.bad));
  await page.locator('#draft-channel').selectOption('channel-1');
  await page.locator('#draft-requirements').fill('16:9，人物突出');
  await page.locator('#draft-comment').fill('Comment: ');
  await page.locator('[data-target="draft-comment"][data-macro="name"]').click();
  check('comment macro inserted',await page.locator('#draft-comment').inputValue()==='Comment: {name}');
  await page.locator('#draft-title').fill('{{name}}');
  await page.locator('[data-action="submit-publish"]').click();
  check('double brace macro rejected',await page.locator('.error-message').innerText().then(t=>t.includes('不支持宏参数')));
  await page.locator('#draft-title').fill('{name}');
  await page.locator('#draft-comment').fill('');
  forceCreateFailure=true;
  await page.locator('[data-action="submit-publish"]').click();
  await page.getByText('上次提交结果待确认。',{exact:false}).waitFor();
  check('draft retained on network/server error',await page.locator('#draft-title').inputValue()==='{name}');
  check('uncertain draft immutable',await page.locator('#draft-title').isDisabled());
  await page.locator('[data-action="submit-publish"]').click();
  await page.getByRole('heading',{name:'发布任务详情',exact:true}).waitFor();
  const createCalls=calls.filter(x=>x.path.endsWith('/tasks')&&x.method==='POST');
  check('idempotent creation retries identical payload',createCalls.length===2&&JSON.stringify(createCalls[0].body)===JSON.stringify(createCalls[1].body));
  check('server task outcome shown',await page.locator('.modal-overlay').innerText().then(t=>t.includes('封面生成中')));
  check('optional comment skipped',await page.locator('.modal-overlay').innerText().then(t=>t.includes('未填写，已跳过')));
  await page.locator('.close-modal').click();
  await page.locator('[data-action="review"][data-id="review-1"]').click();
  await page.locator('[data-action="reject"]').click();
  await page.locator('[data-action="confirm-reject"]').click();
  check('reject feedback mandatory',await page.locator('.inline-error').innerText().then(t=>t.includes('填写修改意见')));
  await page.locator('#reject-reason').fill('增加人物对比度');
  await page.locator('[data-action="confirm-reject"]').click();
  await page.getByRole('heading',{name:'发布任务详情',exact:true}).waitFor();
  check('rejection sends version+feedback',calls.some(x=>x.body?.action==='reject'&&x.body.version===1&&x.body.feedback==='增加人物对比度'));
  await page.locator('.close-modal').click();
  await page.locator('[data-action="review"][data-id="review-2"]').click();
  stale=true;
  await page.locator('[data-action="approve"]').click();
  await page.locator('.inline-error').getByText('当前封面已更新或已被处理，已重新加载最新状态。请重新查看后操作。').waitFor();
  check('stale review reloads version 2',await page.locator('.version-item.selected').innerText().then(t=>t.includes('V2')));
  await page.locator('[data-action="approve"]').click();
  await page.getByRole('heading',{name:'发布任务详情',exact:true}).waitFor();
  check('approve latest version only',calls.some(x=>x.body?.action==='approve'&&x.body.version===2));
  await page.locator('.close-modal').click();
  await page.locator('[data-action="review"][data-id="review-3"]').click();
  await page.locator('[data-action="manual"]').click();
  await page.locator('#manual-cover-file').setInputFiles(fixture);
  await page.locator('.upload-preview-row img').waitFor();
  check('manual local preview first',calls.filter(x=>x.path.endsWith('/covers')).length===0);
  await page.locator('[data-action="confirm-manual"]').click();
  await page.getByRole('heading',{name:'发布任务详情',exact:true}).waitFor();
  check('manual confirmed asset submitted',calls.some(x=>x.body?.action==='manual'&&x.body.cover_asset_id==='asset-1'));
  await page.locator('.close-modal').click();
  await page.locator('#settings-button').click();
  await page.locator('#default-description').fill('{name}\n{desc}\n{url}');
  await page.locator('[data-action="save-settings"]').click();
  await page.locator('#new-publish').click();
  check('saved server default carried into new draft',await page.locator('#draft-description').inputValue()==='{name}\n{desc}\n{url}');
  await page.locator('[data-action="choose-material"]').click();
  await page.locator('[data-action="select-material"]').click();
  await page.locator('[data-action="confirm-material"]').click();
  await page.locator('#draft-channel').selectOption('channel-1');
  await page.locator('[data-action="cover-source"][data-id="local"]').click();
  await page.locator('#draft-cover-file').setInputFiles(fixture);
  await page.locator('.upload-preview-row img').waitFor();
  await page.locator('[data-action="submit-publish"]').click();
  await page.getByRole('heading',{name:'发布任务详情',exact:true}).waitFor();
  check('local cover upload task uses real asset',calls.some(x=>x.body?.cover_source==='local'&&x.body.cover_asset_id==='asset-1'));
  await page.locator('.close-modal').click();
  await page.locator('[data-action="details"][data-id="failed-1"]').last().click();
  await page.locator('[data-action="retry"]').click();
  check('failure retry scoped task route',calls.some(x=>x.path.endsWith('/failed-1/retry')));
  await page.locator('.close-modal').click();
  for(const width of [1366,1920]) { await page.setViewportSize({width,height:900}); check('desktop '+width+' no horizontal body overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)); }
  tasks.unshift(task('deep-link',{current_version:2,versions:[{number:1,url:cover,feedback:'首次生成'},{number:2,url:cover,feedback:'修改后生成'}]}));
  await page.goto(origin + '/youtube-publish.html?task_id=deep-link&version=1');
  await page.getByRole('heading',{name:'审核封面',exact:true}).waitFor();
  check('Feishu deep link opens requested history',await page.locator('.version-item.selected').innerText().then(t=>t.includes('V1')));
  check('historical cover cannot be approved',await page.locator('[data-action="approve"]').isDisabled());
  await page.locator('[data-action="view-version"][data-id="2"]').click();
  await page.locator('[data-action="approve"]').click();
  await page.getByRole('heading',{name:'发布任务详情',exact:true}).waitFor();
  check('explicit latest version deep-link approval',calls.some(x=>x.path.endsWith('/deep-link/review')&&x.body.version===2));
  featureEnabled=false;
  await page.goto(origin + '/youtube-publish.html');
  await page.locator('#page-content:not(.hidden)').waitFor();
  check('feature disabled prevents new submissions',await page.locator('#new-publish').isDisabled());
  loggedIn=false;
  await page.goto(origin + '/youtube-publish.html');
  await page.locator('#page-message').getByText('请先登录',{exact:true}).waitFor();
  check('unauthenticated workspace gated',await page.locator('#page-content').isHidden());
  loggedIn=true;permissionDenied=true;
  await page.goto(origin + '/youtube-publish.html');
  await page.locator('#page-message').getByText('暂无 YouTube 自动发布权限',{exact:true}).waitFor();
  check('server permission denial gated',await page.locator('#page-content').isHidden());
  check('no browser exceptions',errors.length===0);
  check('only authorized feature API used',calls.every(x=>x.path==='/api/ui/topbar'||x.path.startsWith('/api/youtube-auto-publish')));
  return {passed:results.length,checks:results,errors,requestCount:calls.length};
}
