CREATE TABLE `ads_ai`.`ads_tiktok_minis_bid_protection_daily` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Surrogate primary key',
  `record_date` DATE NOT NULL COMMENT 'Bid protection record date',
  `product_id` BIGINT UNSIGNED NOT NULL COMMENT 'Internal TikTok Minis product ID',
  `product_name` VARCHAR(128) NOT NULL COMMENT 'Product display name snapshot',
  `minis_id` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'TikTok Minis ID',
  `advertiser_id` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'TikTok advertiser ID',
  `data_level` VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'CAMPAIGN or ADGROUP',
  `query_id` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'Object ID sent to TikTok API',
  `campaign_id` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT 'TikTok campaign ID',
  `adgroup_id` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT 'TikTok ad group ID',
  `protection_status` VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT 'TikTok bid protection status',
  `status_detail` TEXT NULL COMMENT 'TikTok bid protection status detail',
  `credit_amount_scaled` DECIMAL(30,0) NOT NULL DEFAULT 0 COMMENT 'Raw API credit amount before scaling',
  `credit_amount` DECIMAL(20,5) NOT NULL DEFAULT 0.00000 COMMENT 'Credit amount divided by 100000',
  `currency` VARCHAR(8) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT 'Original credit currency or empty for zero credit',
  `sync_at` DATETIME NOT NULL COMMENT 'Last successful API synchronization time',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Row creation time',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Row update time',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_record_advertiser_level_query` (`record_date`, `advertiser_id`, `data_level`, `query_id`),
  KEY `idx_product_date_level_status_currency` (`product_id`, `record_date`, `data_level`, `protection_status`, `currency`),
  KEY `idx_advertiser_date` (`advertiser_id`, `record_date`),
  KEY `idx_campaign_date` (`campaign_id`, `record_date`),
  KEY `idx_adgroup_date` (`adgroup_id`, `record_date`),
  KEY `idx_status_date` (`protection_status`, `record_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Daily TikTok Minis bid protection history';
