CREATE TABLE IF NOT EXISTS `ads_ai`.`ad_control_action_log` (
  `action_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `preview_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `binding_id` varchar(128) NOT NULL DEFAULT '',
  `rule_id` varchar(128) NOT NULL DEFAULT '',
  `event_key` varchar(191) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `source_type` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'api',
  `actor_user_id` varchar(128) NOT NULL DEFAULT '',
  `product` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `action` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `object_level` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'campaign',
  `run_status` varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '',
  `runner_reason` varchar(255) NOT NULL DEFAULT '',
  `dry_run` tinyint(1) unsigned NOT NULL DEFAULT 0,
  `scanned_count` int unsigned NOT NULL DEFAULT 0,
  `candidate_count` int unsigned NOT NULL DEFAULT 0,
  `matched_count` int unsigned NOT NULL DEFAULT 0,
  `batch_planned_count` int unsigned NOT NULL DEFAULT 0,
  `deferred_count` int unsigned NOT NULL DEFAULT 0,
  `requested_count` int unsigned NOT NULL DEFAULT 0,
  `success_count` int unsigned NOT NULL DEFAULT 0,
  `skipped_count` int unsigned NOT NULL DEFAULT 0,
  `error_count` int unsigned NOT NULL DEFAULT 0,
  `retryable_error_count` int unsigned NOT NULL DEFAULT 0,
  `blocked_count` int unsigned NOT NULL DEFAULT 0,
  `remaining_count` int unsigned NOT NULL DEFAULT 0,
  `criteria_json` mediumtext NOT NULL,
  `results_json` mediumtext NOT NULL,
  `reason_summary_json` text NOT NULL,
  `log_version` smallint unsigned NOT NULL DEFAULT 1,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`action_id`),
  KEY `idx_acl_created` (`created_at`, `action_id`),
  KEY `idx_acl_product_created` (`product`, `created_at`, `action_id`),
  KEY `idx_acl_binding_created` (`binding_id`, `created_at`, `action_id`),
  KEY `idx_acl_event_created` (`event_key`, `created_at`, `action_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
