#!/usr/bin/env python3
"""Build the portable, single-file V3 usage guide.

The source guide keeps screenshots as normal files for easy review and Git
diffs. This script embeds the same JPEG files as data URIs so the standalone
guide can be copied and opened without an assets directory.
"""

from __future__ import annotations

import base64
import hashlib
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / "usage-guide.html"
TARGET = ROOT / "usage-guide-standalone.html"
ASSET_PATTERN = re.compile(r"usage-guide-assets/([A-Za-z0-9._-]+)")


def main() -> None:
    html = SOURCE.read_text(encoding="utf-8")
    source_sha256 = hashlib.sha256(html.encode("utf-8")).hexdigest()
    asset_names = sorted(set(ASSET_PATTERN.findall(html)))
    if not asset_names:
        raise SystemExit("No usage-guide assets were referenced by the source HTML.")

    for asset_name in asset_names:
        asset_path = ROOT / "usage-guide-assets" / asset_name
        if not asset_path.is_file():
            raise SystemExit(f"Missing asset: {asset_path}")
        mime = "image/jpeg" if asset_path.suffix.lower() in {".jpg", ".jpeg"} else "image/png"
        payload = base64.b64encode(asset_path.read_bytes()).decode("ascii")
        html = html.replace(
            f"usage-guide-assets/{asset_name}",
            f"data:{mime};base64,{payload}",
        )

    html = html.replace(
        "<!doctype html>",
        "<!doctype html>\n"
        "<!-- Generated by build_usage_guide.py; edit usage-guide.html instead. -->\n"
        f"<!-- Source-SHA256: {source_sha256} -->",
        1,
    )
    html = html.replace(
        "本手册离线打开不依赖在线字体、CDN 或第三方脚本。",
        "此单文件版本已内嵌全部截图，离线打开不依赖在线字体、CDN、第三方脚本或附件目录。",
        1,
    )
    TARGET.write_text(html, encoding="utf-8", newline="\n")
    print(
        f"Built {TARGET.name}: {len(asset_names)} embedded assets, "
        f"{TARGET.stat().st_size:,} bytes"
    )


if __name__ == "__main__":
    main()
