CREATE TABLE IF NOT EXISTS `ads_ai`.`tiktok_personal_account_snapshot` (
  `source_account_id` BIGINT UNSIGNED NOT NULL COMMENT 'socialkit.social_center_accounts.id',
  `team_id` BIGINT UNSIGNED NOT NULL COMMENT 'SocialKit 团队ID',
  `main_account_id` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '平台主账号ID',
  `external_account_id` VARCHAR(512) NOT NULL DEFAULT '' COMMENT 'TikTok平台对外账号ID',
  `account_name` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '账号展示名称',
  `account_link` VARCHAR(512) NOT NULL DEFAULT '' COMMENT 'TikTok账号主页',
  `post_count` BIGINT NOT NULL DEFAULT 0 COMMENT '帖子数',
  `fan_count` BIGINT NOT NULL DEFAULT 0 COMMENT '粉丝数',
  `view_count` BIGINT NOT NULL DEFAULT 0 COMMENT '播放量',
  `like_count` BIGINT NOT NULL DEFAULT 0 COMMENT '点赞量',
  `comment_count` BIGINT NOT NULL DEFAULT 0 COMMENT '评论量',
  `collect_count` BIGINT NOT NULL DEFAULT 0 COMMENT '收藏量',
  `share_count` BIGINT NOT NULL DEFAULT 0 COMMENT '分享量',
  `access_token` MEDIUMTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL COMMENT 'SocialKit TikTok明文access_token',
  `token_status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1未授权 2正常 3过期',
  `account_status` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1待授权 2已授权 3异常 4信息有误 5已禁用',
  `token_expires_time` BIGINT NOT NULL DEFAULT 0 COMMENT 'access_token过期时间，纳秒时间戳',
  `last_token_checked_time` BIGINT NOT NULL DEFAULT 0 COMMENT 'Token最后巡检时间，纳秒时间戳',
  `disable_publish` TINYINT NOT NULL DEFAULT 0 COMMENT '1禁止发布 0允许发布',
  `has_metric_snapshot` TINYINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '是否匹配到social_account_data指标行',
  `metric_status` INT NOT NULL DEFAULT 0 COMMENT 'social_account_data.status，0表示无指标行',
  `source_account_updated_time` BIGINT NOT NULL DEFAULT 0 COMMENT '授权账号源更新时间，纳秒时间戳',
  `source_metric_updated_at` BIGINT NOT NULL DEFAULT 0 COMMENT '指标源最后更新时间，秒时间戳',
  `is_active` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '本轮源库是否仍为未删除TikTok账号',
  `last_seen_sync_id` CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '最后命中的同步批次ID',
  `last_seen_at` DATETIME(6) NOT NULL COMMENT '最后命中源数据的同步时间',
  `created_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`source_account_id`),
  KEY `idx_tt_snapshot_active_token` (`is_active`, `token_status`, `account_status`, `disable_publish`),
  KEY `idx_tt_snapshot_team` (`team_id`, `is_active`),
  KEY `idx_tt_snapshot_external` (`external_account_id`(191)),
  KEY `idx_tt_snapshot_seen` (`last_seen_sync_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
  COMMENT='SocialKit TikTok个号指标与明文Token当前快照';
